---
apiVersion: v1 
kind: Service
metadata:
  name: fb-lb-svc
  labels:
    app: facebook 

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: facebook 
    

